/**
 * memphis_self_pr_open — A.5.5.
 *
 * Closes a plan by pushing the current branch and opening a PR via gh.
 * Required precondition: every step is `done` or `skipped` (no
 * non-terminal stragglers). We deliberately do NOT require an
 * explicit `memphis_self_review` pass to have run — the operator can
 * choose to skip review for trivial plans, and re-running review on
 * the next turn would catch anything we miss here.
 *
 * Safety:
 * - We push only `--force-with-lease` is intentionally NOT used (a new
 *   branch can't have a stale lease, and we don't want to risk
 *   stepping on a manual operator amend if the branch already exists).
 *   Plain `git push -u origin <branch>` either creates the branch or
 *   fast-forwards; any non-FF rejection surfaces to the operator who
 *   then drives the resolution.
 * - We never call `gh pr merge`. Memphis can OPEN a PR but only the
 *   operator merges. This is the human-review safety bar that S5's
 *   "Out of scope" list explicitly preserves.
 */
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

import { getPlan, setPlanStatus } from '../../modules/self-coding/plan-store.js';
import type { SelfCodingPlan } from '../../modules/self-coding/plan-types.js';

const execFileAsync = promisify(execFile);

export interface SelfPrOpenInput {
  plan_id: string;
  /** Override PR title. Defaults to the plan goal. */
  title?: string;
  /** Override PR body header. Step list is always appended. */
  body_prefix?: string;
  /** Branch override. Defaults to the current git branch. */
  branch?: string;
  /** Base branch for the PR. Defaults to `main`. */
  base?: string;
}

export interface SelfPrOpenOutput {
  ok: boolean;
  plan_id: string;
  pr_url?: string;
  branch?: string;
  error?: string;
}

export interface SelfPrOpenDeps {
  projectRoot?: string;
  rawEnv?: NodeJS.ProcessEnv;
  /** Test seam — override the exec layer. */
  runCommand?: (cmd: string, args: string[], cwd?: string) => Promise<{ stdout: string }>;
}

function defaultRunCommand(
  cmd: string,
  args: string[],
  cwd?: string,
): Promise<{ stdout: string }> {
  return execFileAsync(cmd, args, {
    cwd,
    maxBuffer: 4 * 1024 * 1024,
    timeout: 60_000,
  });
}

function validatePreconditions(plan: SelfCodingPlan): string | null {
  const unfinished = plan.steps.filter(
    (s) => s.status !== 'done' && s.status !== 'skipped',
  );
  if (unfinished.length > 0) {
    return `${unfinished.length} step(s) not done or skipped: ${unfinished.map((s) => s.idx).join(', ')}`;
  }
  if (plan.steps.filter((s) => s.status === 'done').length === 0) {
    return 'plan has no done steps — nothing to ship';
  }
  if (plan.status === 'pr-open') {
    return `plan already has PR open: ${plan.prUrl ?? '<unknown>'}`;
  }
  if (plan.status === 'cancelled' || plan.status === 'done') {
    return `plan is in terminal status: ${plan.status}`;
  }
  return null;
}

export function buildPrBody(plan: SelfCodingPlan, prefix?: string): string {
  const lines: string[] = [];
  if (prefix) {
    lines.push(prefix.trim(), '');
  } else {
    lines.push('## Summary', '', plan.goal, '');
  }
  lines.push('## Steps');
  lines.push('');
  for (const step of plan.steps) {
    const marker = step.status === 'done' ? 'x' : step.status === 'skipped' ? '~' : ' ';
    const artifact = step.artifact ? ` — \`${step.artifact}\`` : '';
    const attempts = step.attempts > 1 ? ` (attempts: ${step.attempts})` : '';
    lines.push(`- [${marker}] **#${step.idx}** ${step.description}${artifact}${attempts}`);
  }
  lines.push('');
  lines.push(`## Plan metadata`);
  lines.push('');
  lines.push(`- plan_id: \`${plan.id}\``);
  lines.push(`- created: ${plan.createdAt}`);
  lines.push(`- updated: ${plan.updatedAt}`);
  lines.push('');
  lines.push('🤖 Generated by `memphis_self_pr_open` (S5 A.5.5)');
  return lines.join('\n');
}

async function detectCurrentBranch(
  projectRoot: string,
  runCommand: NonNullable<SelfPrOpenDeps['runCommand']>,
): Promise<string> {
  const { stdout } = await runCommand('git', ['rev-parse', '--abbrev-ref', 'HEAD'], projectRoot);
  return stdout.trim();
}

function extractPrUrl(output: string): string | null {
  // `gh pr create` prints the PR url on stdout (typically the final
  // non-empty line). The output may also contain a one-line "Creating
  // pull request for ..." line before it. Pick the last line that
  // starts with `https://` so we're robust to gh version drift.
  const lines = output
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    if (lines[i].startsWith('https://')) return lines[i];
  }
  return null;
}

export async function runMemphisSelfPrOpen(
  input: SelfPrOpenInput,
  deps: SelfPrOpenDeps = {},
): Promise<SelfPrOpenOutput> {
  if (!input.plan_id || input.plan_id.trim().length === 0) {
    return { ok: false, plan_id: input.plan_id, error: 'plan_id is required' };
  }
  const plan = getPlan(input.plan_id, deps.rawEnv);
  if (!plan) {
    return { ok: false, plan_id: input.plan_id, error: `plan not found: ${input.plan_id}` };
  }
  const precondition = validatePreconditions(plan);
  if (precondition) {
    return { ok: false, plan_id: plan.id, error: precondition };
  }

  const projectRoot = deps.projectRoot ?? process.cwd();
  const runCommand = deps.runCommand ?? defaultRunCommand;
  const base = input.base ?? 'main';
  let branch: string;
  try {
    branch = input.branch ?? (await detectCurrentBranch(projectRoot, runCommand));
  } catch (err) {
    return {
      ok: false,
      plan_id: plan.id,
      error: `failed to detect current branch: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
  if (branch === base || branch === 'main' || branch === 'master') {
    return {
      ok: false,
      plan_id: plan.id,
      error: `refusing to open PR from default branch ${branch} — switch to a feature branch first`,
    };
  }

  const title = (input.title ?? plan.goal).trim().slice(0, 70);
  const body = buildPrBody(plan, input.body_prefix);

  try {
    await runCommand('git', ['push', '-u', 'origin', branch], projectRoot);
  } catch (err) {
    return {
      ok: false,
      plan_id: plan.id,
      branch,
      error: `git push failed: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  let prUrl: string;
  try {
    const { stdout } = await runCommand(
      'gh',
      ['pr', 'create', '--title', title, '--body', body, '--base', base, '--head', branch],
      projectRoot,
    );
    const extracted = extractPrUrl(stdout);
    if (!extracted) {
      return {
        ok: false,
        plan_id: plan.id,
        branch,
        error: `gh pr create did not return a URL — gh output: ${stdout.slice(-500)}`,
      };
    }
    prUrl = extracted;
  } catch (err) {
    return {
      ok: false,
      plan_id: plan.id,
      branch,
      error: `gh pr create failed: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  setPlanStatus({ planId: plan.id, status: 'pr-open', branch, prUrl }, deps.rawEnv);
  return { ok: true, plan_id: plan.id, pr_url: prUrl, branch };
}
