blank_issues_enabled: true
contact_links:
  - name: Memphis discussions
    url: https://github.com/Memphis-Chains/memphis/discussions
    about: Ask questions and discuss ideas before opening implementation issues.
