#!/usr/bin/env bash
# Stale branch cleanup — generated by Sprint λ-prep 2026-05-06.
# Each branch was audited via gh PR state (merged) + git log diff.
#
# Usage:
#   ./scripts/branch-cleanup-2026-05.sh              # delete all auto-safe
#   ./scripts/branch-cleanup-2026-05.sh review       # show breakdown only
#
# Re-create later via `git checkout -b <name> <commit>` if needed.

set -euo pipefail

# ── 25 branches with MERGED PR (always-safe delete) ───────────────────
MERGED_BRANCHES=(
  feat/sprint-1-v1.5.0-polish              # PR #243
  feat/n8-turnid-consent-propagation       # PR #250
  feat/n37-kartograf-corpus-pipeline       # PR #251
  feat/ci-dep-policy-and-quarterly-gate    # PR #248
  feat/n11-consent-mark-cli                # PR #254
  feat/n40-kartograf-checkpoint            # PR #255
  feat/n9-trajectory-exporter              # PR #253
  feat/n37.2-train-stub                    # PR #259
  feat/n40.2-kartograf-cli                 # PR #258
  feat/n21-embed-cascade                   # PR #256
  feat/n8.2-conversation-id                # PR #257
  chore/q1-exit-test-revised-scope         # PR #260
  release/v1.6.0                           # PR #261 (tag v1.6.0 already pushed)
  feat/n8.2-toolexec-conv-binding          # PR #262
  fix/n40.2-kartograf-codex-followup       # PR #263
  fix/n37.2-train-codex-followup           # PR #264
  docs/n44-kartograf-v2-scout              # PR #265
  feat/rc-drill-v1.6-extension             # PR #266
  feat/v171-clear-drops-chat-history       # PR #299
  release/v1.7.0                           # PR #311 (tag v1.7.0 already pushed)
  fix/s7-backup-pepper-path                # PR #294
  fix/install-root-anchoring-sweep         # PR #314
  fix/env-example-stale-relative-paths     # PR #315
  fix/install-bootstrap-and-init-fallback  # PR #316
  release/v1.7.2                           # PR #317 (tag v1.7.2 already pushed)
)

# ── 4 branches with CLOSED (not merged) PR — operator chose to abandon
# These had unique commits that operator decided not to merge. Safe to
# delete unless you want to preserve the experimental work; commits
# survive in git's reflog for ~30 days regardless.
CLOSED_BRANCHES=(
  feat/s3-self-awareness                   # CLOSED — replaced by later iteration
  feat/s4-app-rs-split-host                # CLOSED
  fix/s6-chat-error-diagnostics            # CLOSED
  feat/v171-provider-model-persist         # CLOSED
)

# ── 1 branch with NO PR ever opened — pure experiment, leave for review
EXPERIMENTAL_BRANCHES=(
  q2/kartograf-phase5-deps  # No PR ever filed; commits not on main. Operator review.
)

if [[ "${1:-}" == "review" ]]; then
  echo "=== ${#MERGED_BRANCHES[@]} branches with MERGED PRs (auto-safe) ==="
  printf '  %s\n' "${MERGED_BRANCHES[@]}"
  echo
  echo "=== ${#CLOSED_BRANCHES[@]} branches with CLOSED PRs (abandoned) ==="
  printf '  %s\n' "${CLOSED_BRANCHES[@]}"
  echo
  echo "=== ${#EXPERIMENTAL_BRANCHES[@]} branches with NO PR (review needed) ==="
  printf '  %s\n' "${EXPERIMENTAL_BRANCHES[@]}"
  echo
  echo "Run without 'review' to delete the merged + closed buckets."
  exit 0
fi

echo "Deleting ${#MERGED_BRANCHES[@]} merged-PR branches..."
for branch in "${MERGED_BRANCHES[@]}"; do
  echo "  delete $branch"
  git push origin --delete "$branch" || echo "    (already gone)"
done

echo
echo "Deleting ${#CLOSED_BRANCHES[@]} closed-PR branches..."
for branch in "${CLOSED_BRANCHES[@]}"; do
  echo "  delete $branch"
  git push origin --delete "$branch" || echo "    (already gone)"
done

echo
echo "Skipped ${#EXPERIMENTAL_BRANCHES[@]} no-PR branches (operator review):"
printf '  %s\n' "${EXPERIMENTAL_BRANCHES[@]}"
echo
echo "Done. Run 'git fetch --prune origin' to update local refs."
