#!/usr/bin/env bash
# Stale branch cleanup — generated by Sprint λ-prep 2026-05-06.
#
# Each line is a separate `git push origin --delete`. Operator
# reviews + comments out anything to keep, then runs the script
# (or runs in batches with `head -N | bash`).
#
# Census: 33 branches older than 7 days with NO open PR.
# Always-keep (main + integration/pre-demo-2026-05-06) and the
# 21 in-flight PR head branches are excluded.
# Re-create later via `git checkout -b <name> <commit>` if needed.

set -euo pipefail

# === IF ANY OF THESE CONTAIN UNMERGED WORK YOU CARE ABOUT,
# ===   COMMENT THE LINE BEFORE RUNNING.
# ===   `git log <branch> ^main` shows what would be lost.

# 2026-04-22 (13 days ago)
git push origin --delete feat/sprint-1-v1.5.0-polish

# 2026-04-23 (12 days ago)
git push origin --delete feat/n8-turnid-consent-propagation

# 2026-04-23 (12 days ago)
git push origin --delete feat/n37-kartograf-corpus-pipeline

# 2026-04-23 (12 days ago)
git push origin --delete feat/ci-dep-policy-and-quarterly-gate

# 2026-04-23 (12 days ago)
git push origin --delete feat/n11-consent-mark-cli

# 2026-04-23 (12 days ago)
git push origin --delete feat/n40-kartograf-checkpoint

# 2026-04-23 (12 days ago)
git push origin --delete feat/n9-trajectory-exporter

# 2026-04-23 (12 days ago)
git push origin --delete feat/n37.2-train-stub

# 2026-04-23 (12 days ago)
git push origin --delete feat/n40.2-kartograf-cli

# 2026-04-23 (12 days ago)
git push origin --delete feat/n21-embed-cascade

# 2026-04-23 (12 days ago)
git push origin --delete feat/n8.2-conversation-id

# 2026-04-23 (12 days ago)
git push origin --delete chore/q1-exit-test-revised-scope

# 2026-04-23 (12 days ago)
git push origin --delete release/v1.6.0

# 2026-04-23 (12 days ago)
git push origin --delete feat/n8.2-toolexec-conv-binding

# 2026-04-23 (12 days ago)
git push origin --delete fix/n40.2-kartograf-codex-followup

# 2026-04-23 (12 days ago)
git push origin --delete fix/n37.2-train-codex-followup

# 2026-04-23 (12 days ago)
git push origin --delete docs/n44-kartograf-v2-scout

# 2026-04-23 (12 days ago)
git push origin --delete feat/rc-drill-v1.6-extension

# 2026-04-25 (10 days ago)
git push origin --delete q2/kartograf-phase5-deps

# 2026-04-26 (9 days ago)
git push origin --delete feat/s3-self-awareness

# 2026-04-26 (9 days ago)
git push origin --delete feat/s4-app-rs-split-host

# 2026-04-26 (9 days ago)
git push origin --delete fix/s6-chat-error-diagnostics

# 2026-04-26 (9 days ago)
git push origin --delete feat/v171-provider-model-persist

# 2026-04-26 (9 days ago)
git push origin --delete feat/v171-clear-drops-chat-history

# 2026-04-26 (9 days ago)
git push origin --delete release/v1.7.0

# 2026-04-27 (9 days ago)
git push origin --delete fix/s7-backup-pepper-path

# 2026-04-27 (9 days ago)
git push origin --delete fix/install-root-anchoring-sweep

# 2026-04-27 (9 days ago)
git push origin --delete fix/env-example-stale-relative-paths

# 2026-04-27 (8 days ago)
git push origin --delete fix/install-bootstrap-and-init-fallback

# 2026-04-27 (8 days ago)
git push origin --delete release/v1.7.2

# 2026-04-27 (8 days ago)
git push origin --delete fix/security-file-perms-and-scan-patterns

# 2026-04-27 (8 days ago)
git push origin --delete docs/readme-version-v172

# 2026-04-28 (7 days ago)
git push origin --delete fix/wiring-w6-security-block-type

